V308CMS.Revenue/Controllers/WidgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using V308CMS.Common;
using V308CMS.Data;

namespace V308CMS.Revenue.Controllers
{
    public class WidgetController : Controller
    {
        public ActionResult Header()
        {
            V308CMSEntities mEntities = new V308CMSEntities();
            MarketRepository marketRepository = new MarketRepository(mEntities);
            AccountRepository accountRepository = new AccountRepository(mEntities);
            HeaderPage mHeaderPage = new HeaderPage();
            List<Market> mList;
            Account mAccount;
            try
            {
                //Check xem dang nhap chưa thi hien thi menu khac
                // && Session["ShopCart"] != null
                if (HttpContext.User.Identity.IsAuthenticated == true && Session["UserId"] != null)
                {
                    //lay thong tin chi tiet user
                    mAccount = accountRepository.LayTinTheoId(Int32.Parse(Session["UserId"].ToString()));
                    mHeaderPage.IsAuthenticated = true;
                    mHeaderPage.Account = mAccount;
                }
                if (Session["ShopCart"] != null)
                    mHeaderPage.ShopCart = (ShopCart)Session["ShopCart"];
                else
                    mHeaderPage.ShopCart = null;
                //lay danh sach nhom tin
                mList = marketRepository.getAll(8);
                mHeaderPage.Market = mList;
                //lay danh sach cac tin theo nhom
                //
                //
                //
                if (Request.Cookies["location"] != null && Request.Cookies["locationname"] != null)
                {
                    ViewBag.location = Int32.Parse(Request.Cookies["location"].Value);
                    ViewBag.locationname = Ultility.convertValueToDistrict(Int32.Parse(Request.Cookies["location"].Value));
                }
                else
                {
                    ViewBag.location = 0;
                    ViewBag.locationname = "Hà Nội";
                }
                //
                return View(mHeaderPage);
            }
            catch (Exception ex)
            {
                return Content("<dx></dx>");
            }
            finally
            {
                mEntities.Dispose();
                marketRepository.Dispose();
            }
        }
        public ActionResult Menu()
        {
            V308CMSEntities mEntities = new V308CMSEntities();
            ProductRepository productRepository = new ProductRepository(mEntities);
            NewsRepository newsRepository = new NewsRepository(mEntities);
            List<ProductType> mProductTypeParent = null;
            List<ProductTypePage> mProductTypePage = new List<ProductTypePage>();
            News mNews;
            ProductTypePageContainer mProductTypePageContainer = new ProductTypePageContainer();
            ImagesRepository imagesRepository = new ImagesRepository(mEntities);
            List<Image> mListImage;
            try
            {
                //lay danh sach nhom tin
                mProductTypeParent = productRepository.getProductTypeParent();
                //lay danh sach cac tin theo nhom
                foreach (ProductType it in mProductTypeParent)
                {
                    ProductTypePage vProductTypePage = new ProductTypePage();
                    vProductTypePage.Id = it.ID;
                    vProductTypePage.Image = it.ImageBanner;
                    vProductTypePage.Name = it.Name;
                    //lay danh sach cac nhom con
                    List<ProductType> mProductTypeChild = productRepository.LayNhomSanPhamTheoTrangVaSeri(1, 10, it.ID);
                    vProductTypePage.List = mProductTypeChild;
                    mProductTypePage.Add(vProductTypePage);
                    //
                    mProductTypePageContainer.List = mProductTypePage;
                    mNews = newsRepository.getFirstNewsWithType(16);
                    mProductTypePageContainer.mNews = mNews;
                    //lay danh sach
                    mListImage = imagesRepository.GetImageByTypeId(1,4);
                    mProductTypePageContainer.ImageList = mListImage;

                }
                return View(mProductTypePageContainer);
            }
            catch (Exception ex)
            {
                return Content("<dx></dx>");
            }
            finally
            {
                mEntities.Dispose();
                productRepository.Dispose();
            }
        }
        public ActionResult Menu2()
        {
            V308CMSEntities mEntities = new V308CMSEntities();
            ProductRepository productRepository = new ProductRepository(mEntities);
            NewsRepository newsRepository = new NewsRepository(mEntities);
            List<ProductType> mProductTypeParent = null;
            List<ProductTypePage> mProductTypePage = new List<ProductTypePage>();
            News mNews;
            ProductTypePageContainer mProductTypePageContainer = new ProductTypePageContainer();
            ImagesRepository imagesRepository = new ImagesRepository(mEntities);
            List<Image> mListImage;
            try
            {
                //lay danh sach nhom tin
                mProductTypeParent = productRepository.getProductTypeParent();
                //lay danh sach cac tin theo nhom
                foreach (ProductType it in mProductTypeParent)
                {
                    ProductTypePage vProductTypePage = new ProductTypePage();
                    vProductTypePage.Id = it.ID;
                    vProductTypePage.Image = it.ImageBanner;
                    vProductTypePage.Name = it.Name;
                    //lay danh sach cac nhom con
                    List<ProductType> mProductTypeChild = productRepository.LayNhomSanPhamTheoTrangVaSeri(1, 10, it.ID);
                    vProductTypePage.List = mProductTypeChild;
                    mProductTypePage.Add(vProductTypePage);
                    //
                    mProductTypePageContainer.List = mProductTypePage;
                    mNews = newsRepository.getFirstNewsWithType(16);
                    mProductTypePageContainer.mNews = mNews;
                    //lay danh sach
                    mListImage = imagesRepository.GetImageByTypeId(1, 4);
                    mProductTypePageContainer.ImageList = mListImage;
                }
                return View(mProductTypePageContainer);
            }
            catch (Exception ex)
            {
                return Content("<dx></dx>");
            }
            finally
            {
                mEntities.Dispose();
                productRepository.Dispose();
            }
        }
        public ActionResult MobileMenu()
        {
            V308CMSEntities mEntities = new V308CMSEntities();
            ProductRepository productRepository = new ProductRepository(mEntities);
            NewsRepository newsRepository = new NewsRepository(mEntities);
            List<ProductType> mProductTypeParent = null;
            List<ProductTypePage> mProductTypePage = new List<ProductTypePage>();
            News mNews;
            ProductTypePageContainer mProductTypePageContainer = new ProductTypePageContainer();
            try
            {
                //lay danh sach nhom tin
                mProductTypeParent = productRepository.getProductTypeParent();
                //lay danh sach cac tin theo nhom
                foreach (ProductType it in mProductTypeParent)
                {
                    ProductTypePage vProductTypePage = new ProductTypePage();
                    vProductTypePage.Id = it.ID;
                    vProductTypePage.Image = it.ImageBanner;
                    vProductTypePage.Name = it.Name;
                    //lay danh sach cac nhom con
                    List<ProductType> mProductTypeChild = productRepository.LayNhomSanPhamTheoTrangVaSeri(1, 10, it.ID);
                    vProductTypePage.List = mProductTypeChild;
                    mProductTypePage.Add(vProductTypePage);
                    //
                    mProductTypePageContainer.List = mProductTypePage;
                    mNews = newsRepository.getFirstNewsWithType(16);
                    mProductTypePageContainer.mNews = mNews;
                }
                return View(mProductTypePageContainer);
            }
            catch (Exception ex)
            {
                return Content("<dx></dx>");
            }
            finally
            {
                mEntities.Dispose();
                productRepository.Dispose();
            }
        }
        public ActionResult HeadMenu()
        {
            V308CMSEntities mEntities = new V308CMSEntities();
            NewsRepository newsRepository = new NewsRepository(mEntities);
            List<NewsGroups> mNewsGroupsList;
            NewsPage mNewsPage = new NewsPage();
            try
            {
                //lay cac menu của MENU
                mNewsGroupsList = newsRepository.LayNhomTinAll();
                //Tao danh sach cac nhom tin
                mNewsPage.HtmlNhomTin = V308HTMLHELPER.TaoDanhSachMenu(mNewsGroupsList);
                return View(mNewsPage);
            }
            catch (Exception ex)
            {
                return Content("Xảy ra lỗi hệ thống ! Vui lòng thử lại.");
            }
            finally
            {
                mEntities.Dispose();
                newsRepository.Dispose();
            }
        }
        public ActionResult Email()
        {
            return View();
        }
        public ActionResult Footer()
        {
            V308CMSEntities mEntities = new V308CMSEntities();
            NewsRepository newsRepository = new NewsRepository(mEntities);
            List<NewsGroups> mNewsGroupsList;

V308CMS.Revenue/Views/Home/Market.cshtml
@model  V308CMS.Data.ProductCategoryPageBox
@{
    ViewBag.Title = "C-FOOD";
    Layout = "~/Views/Layout/_CategoryLayout.cshtml";
    ViewBag.Description = "";
}
<style type="text/css">
    .b1 .b2 .b3 img {
        -webkit-transition: all 500ms ease 0s;
        -o-transition: all 500ms ease 0s;
        transition: all 500ms ease 0s;
        width: 230px;
        height: 200px;
        display: block;
        padding: 12px;
    }

    .b1 .b2 .b3 {
        height: 213px;
    }

    .b1 .b2 .b4 .b5 {
        margin-top: 5px;
        font-size: 16px !important;
        font-weight: normal;
        color: #131313;
    }
</style>
<section class="wrap category no-select">
    <div class="ctnr">
        <section class="cbo-brc">
            <div class="brc-lst"><a class="next" href="//disieuthi.vn/" title="Trang Chủ">Trang Chủ                    </a></div>
            <div class="atc-nm">
                <a href="/trai-cay-tuoi-157/" title="Trái cây tươi">Trái cây tươi                </a>
                <div class="sub-bread is-mn mCustomScrollbar _mCS_1 mCS-autoHide done" style="overflow: visible;">
                    <div id="mCSB_1" class="mCustomScrollBox mCS-minimal-dark mCSB_vertical mCSB_outside" tabindex="0" style="max-height: 200px;">
                    </div>
                    <div id="mCSB_1_scrollbar_vertical" class="mCSB_scrollTools mCSB_1_scrollbar mCS-minimal-dark mCSB_scrollTools_vertical" style="display: block;">
                        <div class="mCSB_draggerContainer">
                            <div id="mCSB_1_dragger_vertical" class="mCSB_dragger" style="position: absolute; min-height: 50px; display: block; height: 67px; max-height: 166px;" oncontextmenu="return false;">
                                <div class="mCSB_dragger_bar" style="line-height: 50px;"></div>
                            </div>
                            <div class="mCSB_draggerRail"></div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- cbo-lst-mrt -->
        <div class="list-category mxClrAft">
            <div class="left-category">
                <div class="slide-category" id="js-vendor-slide1">
                    <ul id="accord-slide-1" class="js-accord-sld" style="display: block; height: 350px; width: 808px; padding: 0px; position: relative; overflow: hidden; list-style: none;">
                        <li class="slider slider-closed" style="top: 0px; z-index: 0; margin: 0px; padding: 0px; float: left; display: block; position: absolute; overflow: hidden; width: 600px; height: 350px; text-indent: 0px; left: 0px; cursor: pointer;"><a href="javascript:;">
                            <img src="//img.disieuthi.vn/quangcao/img05.jpg">
                            <span class="info-slide"><span class="title-slide"></span>
                                <!--<span class="desc-slide">Nhân dịp hè siêu thị Coop-Mart có những chương trình giảm giá đặc biệt, tri ân khách hàng với những ưu đãi lớn dành cho khách hàng thành viên; Thời gian diễn ra từ 02/08/2015 đến 20/08/2015</span>-->
                            </span></a></li>
                    </ul>
                </div>
                @if (Model.List != null)
                { 
                @foreach (V308CMS.Data.ProductCategoryPage it in Model.List)
                {
                    if (it.List.Count > 0)
                    {
                    <section class="cbo-hp vd">
                        <div class="cbo-hp-head mxClrAft"><a class="hp-ttl" href="/@V308CMS.Common.Ultility.LocDau(@Model.Market.UserName)-m@(@it.Id).html">@it.Name        </a><a href="/@V308CMS.Common.Ultility.LocDau(@Model.Market.UserName)-m@(@it.Id).html" class="hp-mre">Xem tất cả            <span class="fa fa-angle-right"></span></a></div>
                        <!-- cbo-hp-head -->
                        <div class="cbo-hp-cnt mxClrAft cat-hp">
                            <div class="rht-cat-hp" id="list_product_1">
                                <div class="b1">
                                    @foreach (V308CMS.Data.Product ht in it.List)
                                    {
                                       <div class="b2 cq" data-id="13015" style="height: 330px;">
                                           
                                            <a href="/@V308CMS.Common.Ultility.LocDau(@ht.Name)-d@(@ht.ID).html" class="b3" style="margin:0px;" title="Rau muống goodlife greens">
                                                <img class="lazy-loaded" data-src="@ht.Image" alt="Rau muống goodlife greens" src="http://cleanfoodvn.vn@(@ht.Image)">
                                            </a>
                                            <div class="b4">
                                                <a class="b5" href="/@V308CMS.Common.Ultility.LocDau(@ht.Name)-d@(@ht.ID).html" title="@ht.Name">@ht.Name</a>
                                                <div class="b6" style="display: inline-block; margin: auto; overflow: inherit;">
                                                    <span style="color: #be1a19; font-size: 22px; line-height: 36px;">@String.Format("{0: 0,0}", (ht.Price - ((ht.Price / 100) * ht.SaleOff)))đ</span>
                                                    @if (ht.SaleOff > 0)
                                                    { 
                                                        <span style="text-decoration: line-through; font-size: 14px; margin: 0 6px;">@String.Format("{0: 0.0}", (ht.Price))đ</span>
                                                        <span style="color: #fff; background: #e61010; display: inline-block; padding: 0px 7px 4px; border-radius: 22px; height: 15px; margin-left: 2px; line-height: 22px;">-@ht.SaleOff%</span>
                                                    }

                                                </div>
                                                <div class="b6">
                                                    @String.Format("{0: 0,0}", (ht.Price - ((ht.Price / 100) * ht.SaleOff)))đ/@V308CMS.Common.ConverterUlti.ConverUnitWeight(ht.Group)
                                                </div>
                                                <div class="b7"><span class="rating is-rating only-display" data-value="@ht.getReview()"><span></span><span></span><span></span><span></span><span></span></span><span style="display: inline; font-size: 15px; margin-left: 3px;">(@ht.getReview())</span></div>
                                            </div>
                                            <div class="b4">
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </section>
                    }
                }
                }
                
            </div>
            @*  <div class="right-category">
                <section class="ifo-mrt"><a class="mrt-head"><span class="avsp">
                    <img src="//img.disieuthi.vn/Media/logo/lytuong-2.png" alt="Ideal Foods">
                </span>
                    <h3><span class="v1">@Model.Market.UserName        </span></h3>
                    <span class="rating is-rating only-display" data-value="3"><span></span><span></span><span></span><span></span><span></span></span>
                    <!--<span class="tile-flag-title"></span>-->
                </a>
                    <div class="mrt-dtl">
                        <div class="rw-mrt"><span class="rw-mrt-tl">Số lượt mua:            </span><span class="rw-mrt-ct">313            </span>
                            <div class="fa fa-question-circle q-ifo">
                                <div class="content">Số lượt mua sản phẩm của nhà cung cấp này.</div>
                            </div>
                        </div>
                        <div class="rw-mrt"><span class="rw-mrt-tl">Số người mua:            </span><span class="rw-mrt-ct">193            </span>
                            <div class="fa fa-question-circle q-ifo">
                                <div class="content">Số người đã mua sản phẩm của nhà cung cấp này.</div>
                            </div>
                        </div>
                        <div class="rw-mrt"><span class="rw-mrt-tl">Số giỏ hàng:            </span><span class="rw-mrt-ct">343            </span>
                            <div class="fa fa-question-circle q-ifo">
                                <div class="content">Số lượng giỏ hàng sản phẩm của nhà cung cấp được tạo.</div>
                            </div>
                        </div>
                    </div>
                    <!-- mrt-dtl -->
                    <div class="mrt-ft">
                        <div class="promo-mart" id="js-vendor-description">@Model.Market.Sumary</div>
                        <a class="js-show-vendor" data-id="57" data-name="Ideal Foods" href="javascript:void();">Xem chi tiết</a>
                    </div>
                    <!-- mrt-ft -->
                </section>
                @Html.Action("Right", "Widget")
            </div>*@
        </div>
    </div>
    <div class="clr"></div>
</section>

V308CMS.Revenue/Views/Home/MarketCategory.cshtml
@model  V308CMS.Data.ProductCategoryPage
@{
    ViewBag.Title = "C-FOOD";
    Layout = "~/Views/Layout/_CategoryLayout.cshtml";
    ViewBag.Description = "";
}
<style type="text/css">
    .b1 .b2 .b3 img {
        -webkit-transition: all 500ms ease 0s;
        -o-transition: all 500ms ease 0s;
        transition: all 500ms ease 0s;
        width: 230px;
        height: 200px;
        display: block;
        padding: 12px;
    }

    .b1 .b2 .b3 {
        height: 213px;
    }

    .b1 .b2 .b4 .b5 {
        margin-top: 5px;
        font-size: 16px !important;
        font-weight: normal;
        color: #131313;
    }
</style>
<section class="wrap category no-select">
    <div class="ctnr">
        <section class="cbo-brc">
            <div class="brc-lst"><a class="next" href="/@V308CMS.Common.Ultility.LocDau(@Model.Market.UserName)" title="Trang Chủ">@Model.Market.UserName                    </a></div>
            <div class="atc-nm">
                <a href="/@V308CMS.Common.Ultility.LocDau(@Model.Market.UserName)-m@(@Model.Id).html" title="@Model.Name">@Model.Name </a>
                <div class="sub-bread is-mn mCustomScrollbar _mCS_1 mCS-autoHide done" style="overflow: visible;">
                    <div id="mCSB_1" class="mCustomScrollBox mCS-minimal-dark mCSB_vertical mCSB_outside" tabindex="0" style="max-height: 200px;">
                    </div>
                    <div id="mCSB_1_scrollbar_vertical" class="mCSB_scrollTools mCSB_1_scrollbar mCS-minimal-dark mCSB_scrollTools_vertical" style="display: block;">
                        <div class="mCSB_draggerContainer">
                            <div id="mCSB_1_dragger_vertical" class="mCSB_dragger" style="position: absolute; min-height: 50px; display: block; height: 67px; max-height: 166px;" oncontextmenu="return false;">
                                <div class="mCSB_dragger_bar" style="line-height: 50px;"></div>
                            </div>
                            <div class="mCSB_draggerRail"></div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- cbo-lst-mrt -->
        <div class="list-category mxClrAft">
            <div class="left-category">
                <div class="slide-category" id="js-vendor-slide1">
                    <ul id="accord-slide-1" class="js-accord-sld" style="display: block; height: 350px; width: 808px; padding: 0px; position: relative; overflow: hidden; list-style: none;">
                        <li class="slider slider-closed" style="top: 0px; z-index: 0; margin: 0px; padding: 0px; float: left; display: block; position: absolute; overflow: hidden; width: 600px; height: 350px; text-indent: 0px; left: 0px; cursor: pointer;"><a href="javascript:;">
                            <img src="//img.disieuthi.vn/quangcao/img05.jpg">
                            <span class="info-slide"><span class="title-slide"></span>
                            </span></a></li>
                    </ul>
                </div>
                <section class="cbo-hp vd">
                    <div class="cbo-hp-head mxClrAft"><a class="hp-ttl" href="javascript:void();">Danh sách sản phẩm        </a></div>
                    <!-- cbo-hp-head -->
                    <div class="cbo-hp-cnt mxClrAft cat-hp">
                        <div class="rht-cat-hp" id="list_product_57">
                            <div class="b1">
                                @foreach (V308CMS.Data.Product ht in Model.List)
                                {
                                    <div class="b2 cq" data-id="13015" style="height: 330px;">

                                        <a href="/@V308CMS.Common.Ultility.LocDau(@ht.Name)-d@(@ht.ID).html" class="b3" style="margin:0px;" title="Rau muống goodlife greens">
                                            <img class="lazy-loaded" data-src="@ht.Image" alt="Rau muống goodlife greens" src="http://cleanfoodvn.vn@(@ht.Image)">
                                        </a>
                                        <div class="b4">
                                            <a class="b5" href="/@V308CMS.Common.Ultility.LocDau(@ht.Name)-d@(@ht.ID).html" title="@ht.Name">@ht.Name</a>
                                            <div class="b6" style="display: inline-block; margin: auto; overflow: inherit;">
                                                <span style="color: #be1a19; font-size: 22px; line-height: 36px;">@String.Format("{0: 0,0}", (ht.Price - ((ht.Price / 100) * ht.SaleOff)))đ</span>
                                                @if (ht.SaleOff > 0)
                                                { 
                                                    <span style="text-decoration: line-through; font-size: 14px; margin: 0 6px;">@String.Format("{0: 0.0}", (ht.Price))đ</span>
                                                    <span style="color: #fff; background: #e61010; display: inline-block; padding: 0px 7px 4px; border-radius: 22px; height: 15px; margin-left: 2px; line-height: 22px;">-@ht.SaleOff%</span>
                                                }

                                            </div>
                                            <div class="b6">
                                                @String.Format("{0: 0,0}", (ht.Price - ((ht.Price / 100) * ht.SaleOff)))đ/@V308CMS.Common.ConverterUlti.ConverUnitWeight(ht.Group)
                                            </div>
                                            <div class="b7"><span class="rating is-rating only-display" data-value="@ht.getReview()"><span></span><span></span><span></span><span></span><span></span></span><span style="display: inline; font-size: 15px; margin-left: 3px;">(@ht.getReview())</span></div>
                                        </div>
                                        <div class="b4">
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                        <div class="page-nav">
                            <div class="pg mxClrAft nav-sld">
                                <div class="n item-pagi-sld" title=""><a href="/@V308CMS.Common.Ultility.LocDau(@Model.Market.UserName)-m@(@Model.Id).html?pPage=@Model.BackPage">Back</a></div>
                                <div class="n item-pagi-sld atv" title=""><a href="/@V308CMS.Common.Ultility.LocDau(@Model.Market.UserName)-m@(@Model.Id).html?pPage=@Model.Page">@Model.Page</a></div>
                                <div class="n item-pagi-sld" title=""><a href="/@V308CMS.Common.Ultility.LocDau(@Model.Market.UserName)-m@(@Model.Id).html?pPage=@Model.NextPage">Next</a></div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
          @*  <div class="right-category">
                @Html.Action("Right", "Widget")
            </div>*@
        </div>
    </div>
    <div class="clr"></div>
</section>

V308CMS.Revenue/Views/Home/News.cshtml
@model V308CMS.Data.NewsPage
@{
    ViewBag.Title = "News";
    Layout = "~/Views/Layout/_NewsLayout.cshtml";
}
<link rel="stylesheet" href="/Content/Css/style.css?v=0.0.5">
<section class="wrap category no-select">
    <div class="ctnr">
        <section class="cbo-brc">
            <div class="brc-lst"><a class="next" href="/" title="Trang Chủ">Trang Chủ</a></div>
        </section>
        <!-- cbo-lst-mrt -->
        <div class="list-category mxClrAft">
            <div class="left-category">
                <section class="right-cmt-page">
                    <div class="title-cmt-page" style="color: #00a651; font-size: 24px; font-family: Roboto-Medium; line-height: 40px; border-bottom: 1px solid #efefef; margin-bottom: 20px; padding-bottom: 15px;">@Model.NewsGroups.Name</div>
                    <section class="grounpStoryList page-cmt-content">
                     @Html.Raw(Model.Html)
                    </section>
                </section>
                 <div class="page-nav">
                            <div class="pg mxClrAft nav-sld">
                                <div class="n item-pagi-sld" title=""><a href="/@V308CMS.Common.Ultility.LocDau(@Model.NewsGroups.Name)-group@(@Model.NewsGroups.ID).html?pPage=@Model.BackPage">Back</a></div>
                                <div class="n item-pagi-sld atv" title=""><a href="/@V308CMS.Common.Ultility.LocDau(@Model.NewsGroups.Name)-group@(@Model.NewsGroups.ID).html?pPage=@Model.Page">@Model.Page</a></div>
                                <div class="n item-pagi-sld" title=""><a href="/@V308CMS.Common.Ultility.LocDau(@Model.NewsGroups.Name)-group@(@Model.NewsGroups.ID).html?pPage=@Model.NextPage">Next</a></div>
                            </div>
                        </div>
            </div>
          @*  <div class="right-category">
                @Html.Action("Right", "Widget")
            </div>*@
        </div>
    </div>
    <div class="clr"></div>
</section>

V308CMS.Revenue/Views/Home/NewsDetail.cshtml
@model V308CMS.Data.NewsPage
@{
    ViewBag.Title = "ChiTietTin";
    Layout = "~/Views/Layout/_NewsLayout.cshtml";
}
<section class="wrap category no-select">
    <div class="ctnr">
        <section class="cbo-brc">
            <div class="brc-lst"><a class="next" href="/" title="Trang Chủ">Trang Chủ                </a><a class="next" href="javascript:void(0)" title="Thông tin chung">Thông tin chung                </a></div>
            <a class="atc-nm" href="/ve-chung-toi.html" title="Về chúng tôi">Về chúng tôi</a>
        </section>
        <!-- cbo-lst-mrt -->
        <div class="list-category mxClrAft">
            <div class="left-category">
                <section class="right-cmt-page">
                    <div class="title-cmt-page" style="color: #00a651; font-size: 24px; font-family: Roboto-Medium; line-height: 40px; border-bottom: 1px solid #efefef; margin-bottom: 20px; padding-bottom: 15px;">@Model.pNews.Title</div>
                    <section class="page-cmt-content">
                       @Html.Raw(@Model.pNews.Detail)
                    </section>
                </section>
            </div>
           @* <div class="right-category">
                @Html.Action("Right", "Widget")
            </div>*@
        </div>
    </div>
    <div class="clr"></div>
</section>